import { PING_GROUP_SCRIPT_VARS } from './ping-groups'
import { DEFAULT_NETWORK_SPEED_UNIT } from './network-speed'

export const RUNTIME_SCRIPT_VARS = {
  ...PING_GROUP_SCRIPT_VARS,
  PROBE_NETWORK_SPEED_UNIT: DEFAULT_NETWORK_SPEED_UNIT,
}
